name: eschool2022
channels:
  - default
  - conda-forge
dependencies:
  - astropy
  - ipython
  - ipywidgets~=7.7.0
  - jupyterlab
  - matplotlib
  - seaborn
  - numba
  - numpy
  - pandas
  - pip
  - pytables
  - pytest
  - pytest-cov
  - python=3.10
  - rise~=5.7.1
  - scikit-learn
  - scipy
  - twine
  - wheel
  - line_profiler
  - memory_profiler
  - snakeviz
  - nbmake
  - h5py
  - ipympl
  - pip:
    - build
