name: Base env test

on: [push, pull_request]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        echo "source $CONDA/etc/profile.d/conda.sh" >> $HOME/.bash_profile
        conda info

    - name: Install dependencies
      shell: bash -leo pipefail {0}
      run: |
        conda install mamba -n base -c conda-forge
        mamba env create --file environment.yml --name eschool2022
        echo "conda activate eschool2022" >> $HOME/.bash_profile
    - name: Lint with flake8
      shell: bash -leo pipefail {0}
      run: |
        mamba install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test notebooks
      shell: bash -leo pipefail {0}
      run: |
        python -m ipykernel install --user --name eschool2022
        pytest --nbmake --nbmake-kernel=eschool2022 --ignore=julia --ignore=testing


  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: ["windows-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          echo "source $CONDA/etc/profile.d/conda.sh" >> $HOME/.bash_profile
          conda info
      - name: Install dependencies
        shell: bash -leo pipefail {0}
        run: |
          conda env create --file environment.yml --name eschool2022
          echo "conda activate eschool2022" >> $HOME/.bash_profile
#       - name: Test notebooks
#         shell: bash -leo pipefail {0}
#         run: |
#           python -m ipykernel install --user --name eschool2022
#           pytest --nbmake --nbmake-kernel=eschool2022 **/*ipynb
